Traceback (most recent call last):
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/psutil/_common.py", line 441, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/psutil/_psosx.py", line 343, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/psutil/_common.py", line 444, in wrapper
    return fun(self)
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/psutil/_psosx.py", line 370, in _get_kinfo_proc
    ret = cext.proc_kinfo_oneshot(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from sysctl(kinfo_proc), len == 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/psutil/__init__.py", line 361, in _init
    self.create_time()
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/psutil/__init__.py", line 717, in create_time
    self._create_time = self._proc.create_time()
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/psutil/_psosx.py", line 343, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/psutil/_psosx.py", line 468, in create_time
    return self._get_kinfo_proc()[kinfo_proc_map['ctime']]
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/psutil/_psosx.py", line 348, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=39707)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/airflow/__main__.py", line 62, in main
    args.func(args)
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/airflow/cli/commands/webserver_command.py", line 485, in webserver
    run_command_with_daemon_option(
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/airflow/cli/commands/daemon_utils.py", line 81, in run_command_with_daemon_option
    callback()
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/airflow/cli/commands/webserver_command.py", line 488, in <lambda>
    callback=lambda: start_and_monitor_gunicorn(args),
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/airflow/cli/commands/webserver_command.py", line 471, in start_and_monitor_gunicorn
    gunicorn_master_proc = psutil.Process(gunicorn_master_proc_pid)
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/psutil/__init__.py", line 332, in __init__
    self._init(pid)
  File "/Users/mohamedaminemrabet/miniforge3/envs/DSP/lib/python3.9/site-packages/psutil/__init__.py", line 373, in _init
    raise NoSuchProcess(pid, msg='process PID not found')
psutil.NoSuchProcess: process PID not found (pid=39707)
